name: Security and Docker Build Pipeline

on:
    push:
        branches:
            - main
env:
    DOCKER_IMAGE: security-example
    DOCKER_IMAGE_VERSION: latest
jobs:
    security-scan-and-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@v2

            - name: Check Snyk Authentication
              uses: snyk/actions/node@master
              with:
                  args: auth
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

            - name: Run Snyk Scan
              uses: snyk/actions/node@master
              with:
                  args: test
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

            - name: Build Docker Image
              run: |
                  docker build -t ${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_VERSION}} .

            - name: Trivy Docker Image Scan
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "image"
                  scan-ref: "${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_VERSION}}"

            # - name: Log in to Docker Hub
            #   uses: docker/login-action@v3
            #   with:
            #     username: ${{ secrets.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKER_PASSWORD }}

            # - name: Push Docker Image
            #   run: |
            #     docker tag my-next-app:latest mydockerhubuser/my-next-app:latest
            #     docker push mydockerhubuser/my-next-app:latest
